language: ruby
services:
  - postgresql
before_script:
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
script:
- bundle exec rubocop
- bundle exec rails test
